linters:
  enable-all: true
  disable:
    - lll
    - gochecknoinits
    - gochecknoglobals
    - funlen
    - whitespace
    - wsl
    - gomnd
    - goerr113 

linters-settings:
  godox:
    # report any comments starting with keywords, this is useful for TODO or FIXME comments that
    # might be left in the code accidentally and should be resolved before merging
    keywords:
      - FIXME
