version: "2.4"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 6.0.0.0/24

services:
  hub1:
    container_name: hub1
    hostname: hub1
    image: toolset.safing.network/dev
    entrypoint: ["/bin/sh", "-c"]
    command: ["/opt/hub1 --data /opt/data --log trace --bootstrap-file /opt/shared/bootstrap.dsd"]
    # command: ["ifconfig"]
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub1:ro
      - ${SPN_TEST_DATA_DIR}/hub1:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.11

  hub2:
    container_name: hub2
    hostname: hub2
    image: toolset.safing.network/dev
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo waiting for 6s; sleep 6; /opt/hub2 --data /opt/data --log trace --bootstrap-file /opt/shared/bootstrap.dsd"]
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub2:ro
      - ${SPN_TEST_DATA_DIR}/hub2:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.12

  hub3:
    container_name: hub3
    hostname: hub3
    image: toolset.safing.network/dev
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo waiting for 12s; sleep 12; /opt/hub3 --data /opt/data --log trace --bootstrap-file /opt/shared/bootstrap.dsd"]
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub3:ro
      - ${SPN_TEST_DATA_DIR}/hub3:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.13

  hub4:
    container_name: hub4
    hostname: hub4
    image: toolset.safing.network/dev
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo waiting for 18s; sleep 18; /opt/hub4 --data /opt/data --log trace --bootstrap-file /opt/shared/bootstrap.dsd"]
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub4:ro
      - ${SPN_TEST_DATA_DIR}/hub4:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.14

  hub5:
    container_name: hub5
    hostname: hub5
    image: toolset.safing.network/dev
    entrypoint: ["/bin/sh", "-c"]
    command: ["echo waiting for 24s; sleep 24; /opt/hub5 --data /opt/data --log trace --bootstrap-file /opt/shared/bootstrap.dsd"]
    volumes:
      - ${SPN_TEST_BIN}:/opt/hub5:ro
      - ${SPN_TEST_DATA_DIR}/hub5:/opt/data
      - ${SPN_TEST_SHARED_DATA_DIR}:/opt/shared
    networks:
      default:
        ipv4_address: 6.0.0.15
